In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/mock_ige_cytokine_behavior.csv')
df.head()

,subject_id,age,sex,IgE_IU_mL,IL4_pg_mL,IL6_pg_mL,IL10_pg_mL,TNFa_pg_mL,IFNg_pg_mL,behavior_score,behavior_group
0,S001,4,F,54.47,4.71,3.40,5.35,1.88,3.11,24.0,Atypical
1,S002,6,F,34.05,3.49,3.72,2.04,1.23,1.99,13.4,Typical
2,S003,11,F,42.36,8.27,2.53,5.84,1.95,2.66,39.4,Atypical
3,S004,7,M,122.89,13.42,7.12,NaN,6.24,5.43,19.6,Atypical
4,S005,10,M,30.87,3.87,1.96,3.90,1.39,2.64,22.4,Atypical

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject_id      150 non-null    object
 1   age             150 non-null    int64
 2   sex             150 non-null    object
 3   IgE_IU_mL       150 non-null    float64
 4   IL4_pg_mL       150 non-null    float64
 5   IL6_pg_mL       150 non-null    float64
 6   IL10_pg_mL      145 non-null    float64
 7   TNFa_pg_mL      145 non-null    float64
 8   IFNg_pg_mL      150 non-null    float64
 9   behavior_score  150 non-null    float64
 10  behavior_group  150 non-null    object
dtypes: float64(7), int64(1), object(3)
memory usage: 13.0+ KB

In [5]:
df.isnull().sum()

subject_id        0
age               0
sex               0
IgE_IU_mL         0
IL4_pg_mL         0
IL6_pg_mL         0
IL10_pg_mL        5
TNFa_pg_mL        5
IFNg_pg_mL        0
behavior_score    0
behavior_group    0
dtype: int64

In [6]:
df.describe()

,age,IgE_IU_mL,IL4_pg_mL,IL6_pg_mL,IL10_pg_mL,TNFa_pg_mL,IFNg_pg_mL,behavior_score
count,150.000000,150.000000,150.00000,150.000000,145.000000,145.000000,150.000000,150.000000
mean,7.960000,45.789533,5.30080,2.935800,3.716621,2.757034,2.935333,19.159333
std,2.729112,47.579650,3.93373,1.662469,2.155633,1.825223,1.481370,8.633205
min,4.000000,3.370000,0.92000,0.540000,0.950000,0.650000,0.710000,0.000000
25%,5.000000,17.332500,2.91500,1.670000,2.260000,1.610000,1.850000,13.900000
50%,8.000000,32.330000,4.39000,2.645000,3.150000,2.250000,2.645000,18.700000
75%,10.000000,53.995000,6.25250,3.677500,4.540000,3.380000,3.540000,24.100000
max,12.000000,337.490000,28.83000,8.540000,14.770000,12.230000,7.660000,42.100000

In [7]:
print("Rows:", df.shape[0], "Columns:", df.shape[1])

Rows: 150 Columns: 11

In [8]:
df.isnull().sum()

subject_id        0
age               0
sex               0
IgE_IU_mL         0
IL4_pg_mL         0
IL6_pg_mL         0
IL10_pg_mL        5
TNFa_pg_mL        5
IFNg_pg_mL        0
behavior_score    0
behavior_group    0
dtype: int64